"""match table refactor

Revision ID: 45c0837ce824
Revises: ebd3bdf1ce7b
Create Date: 2021-03-16 22:10:07.643242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c0837ce824'
down_revision = 'ebd3bdf1ce7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('matches', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('matches', 'matched_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'matcher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'matcher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'matched_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('matches', 'updated_at')
    op.drop_column('matches', 'id')
    op.drop_column('matches', 'created_at')
    # ### end Alembic commands ###
